"""add_field_worker_models

Revision ID: db714d235900
Revises: 66f98182a0b2
Create Date: 2026-09-14 16:15:00.721681+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'db714d235900'
down_revision: Union[str, None] = '66f98182a0b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('authority_id', sa.UUID(), nullable=False),
    sa.Column('zone', sa.String(length=100), nullable=True),
    sa.Column('team', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['authority_id'], ['authorities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.add_column('evidence', sa.Column('evidence_phase', sa.String(length=20), nullable=True))
    op.add_column('incidents', sa.Column('assigned_worker_id', sa.UUID(), nullable=True))
    op.add_column('incidents', sa.Column('worker_status', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_incidents_assigned_worker_id'), 'incidents', ['assigned_worker_id'], unique=False)
    op.create_foreign_key('fk_incidents_assigned_worker', 'incidents', 'worker_profiles', ['assigned_worker_id'], ['id'], ondelete='SET NULL')
    
    # Update User role constraint
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_authority_check;")
    op.execute("ALTER TABLE users ADD CONSTRAINT users_role_authority_check CHECK ((role IN ('citizen', 'admin') AND authority_id IS NULL) OR (role IN ('authority', 'field_worker') AND authority_id IS NOT NULL));")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_authority_check;")
    op.execute("ALTER TABLE users ADD CONSTRAINT users_role_authority_check CHECK ((role IN ('citizen', 'admin') AND authority_id IS NULL) OR (role = 'authority' AND authority_id IS NOT NULL));")

    op.drop_constraint('fk_incidents_assigned_worker', 'incidents', type_='foreignkey')
    op.drop_index(op.f('ix_incidents_assigned_worker_id'), table_name='incidents')
    op.drop_column('incidents', 'worker_status')
    op.drop_column('incidents', 'assigned_worker_id')
    op.drop_column('evidence', 'evidence_phase')
    op.drop_table('worker_profiles')
    # ### end Alembic commands ###
