"""phase_2_tables

Revision ID: 43389400dc2b
Revises: 0002_domain_foundation
Create Date: 2026-09-12 09:25:22.471978+00:00
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '43389400dc2b'
down_revision: Union[str, None] = '0002_domain_foundation'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    
    
    
    
    op.drop_constraint(op.f('authorities_short_code_key'), 'authorities', type_='unique')
    op.drop_index(op.f('ix_authorities_short_code'), table_name='authorities')
    op.create_index(op.f('ix_authorities_short_code'), 'authorities', ['short_code'], unique=True)
    op.alter_column('evidence', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_constraint(op.f('incidents_reference_number_key'), 'incidents', type_='unique')
    op.drop_index(op.f('ix_incidents_reference_number'), table_name='incidents')
    op.create_index(op.f('ix_incidents_reference_number'), 'incidents', ['reference_number'], unique=True)
    op.drop_index(op.f('ix_jurisdictions_boundary'), table_name='jurisdictions', postgresql_using='gist', postgresql_where='(boundary IS NOT NULL)')
    op.drop_constraint(op.f('jurisdictions_code_key'), 'jurisdictions', type_='unique')
    op.drop_index(op.f('ix_jurisdictions_code'), table_name='jurisdictions')
    op.create_index(op.f('ix_jurisdictions_code'), 'jurisdictions', ['code'], unique=True)
    op.create_index('idx_jurisdictions_boundary', 'jurisdictions', ['boundary'], unique=False, postgresql_using='gist')
    op.drop_index(op.f('ix_locations_geom'), table_name='locations', postgresql_using='gist', postgresql_where='(geom IS NOT NULL)')
    op.create_index('idx_locations_geom', 'locations', ['geom'], unique=False, postgresql_using='gist')
    op.drop_constraint(op.f('priorities_incident_id_key'), 'priorities', type_='unique')
    op.drop_index(op.f('ix_priorities_incident_id'), table_name='priorities')
    op.create_index(op.f('ix_priorities_incident_id'), 'priorities', ['incident_id'], unique=True)
    op.alter_column('slas', 'state',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.Enum('PENDING', 'DUE', 'OVERDUE', 'ESCALATION_ELIGIBLE', 'RESOLVED', name='accountabilitystate', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_constraint(op.f('slas_incident_id_key'), 'slas', type_='unique')
    op.drop_index(op.f('ix_slas_incident_id'), table_name='slas')
    op.create_index(op.f('ix_slas_incident_id'), 'slas', ['incident_id'], unique=True)
    op.create_index(op.f('ix_slas_due_at'), 'slas', ['due_at'], unique=False)
    op.drop_constraint(op.f('verification_records_incident_id_key'), 'verification_records', type_='unique')
    op.drop_index(op.f('ix_verification_records_incident_id'), table_name='verification_records')
    op.create_index(op.f('ix_verification_records_incident_id'), 'verification_records', ['incident_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_records_incident_id'), table_name='verification_records')
    op.create_index(op.f('ix_verification_records_incident_id'), 'verification_records', ['incident_id'], unique=False)
    op.create_unique_constraint(op.f('verification_records_incident_id_key'), 'verification_records', ['incident_id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_slas_due_at'), table_name='slas')
    op.drop_index(op.f('ix_slas_incident_id'), table_name='slas')
    op.create_index(op.f('ix_slas_incident_id'), 'slas', ['incident_id'], unique=False)
    op.create_unique_constraint(op.f('slas_incident_id_key'), 'slas', ['incident_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('slas', 'state',
               existing_type=sa.Enum('PENDING', 'DUE', 'OVERDUE', 'ESCALATION_ELIGIBLE', 'RESOLVED', name='accountabilitystate', native_enum=False),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_priorities_incident_id'), table_name='priorities')
    op.create_index(op.f('ix_priorities_incident_id'), 'priorities', ['incident_id'], unique=False)
    op.create_unique_constraint(op.f('priorities_incident_id_key'), 'priorities', ['incident_id'], postgresql_nulls_not_distinct=False)
    op.drop_index('idx_locations_geom', table_name='locations', postgresql_using='gist')
    op.create_index(op.f('ix_locations_geom'), 'locations', ['geom'], unique=False, postgresql_using='gist', postgresql_where='(geom IS NOT NULL)')
    op.drop_index('idx_jurisdictions_boundary', table_name='jurisdictions', postgresql_using='gist')
    op.drop_index(op.f('ix_jurisdictions_code'), table_name='jurisdictions')
    op.create_index(op.f('ix_jurisdictions_code'), 'jurisdictions', ['code'], unique=False)
    op.create_unique_constraint(op.f('jurisdictions_code_key'), 'jurisdictions', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_jurisdictions_boundary'), 'jurisdictions', ['boundary'], unique=False, postgresql_using='gist', postgresql_where='(boundary IS NOT NULL)')
    op.drop_index(op.f('ix_incidents_reference_number'), table_name='incidents')
    op.create_index(op.f('ix_incidents_reference_number'), 'incidents', ['reference_number'], unique=False)
    op.create_unique_constraint(op.f('incidents_reference_number_key'), 'incidents', ['reference_number'], postgresql_nulls_not_distinct=False)
    op.alter_column('evidence', 'file_size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_authorities_short_code'), table_name='authorities')
    op.create_index(op.f('ix_authorities_short_code'), 'authorities', ['short_code'], unique=False)
    op.create_unique_constraint(op.f('authorities_short_code_key'), 'authorities', ['short_code'], postgresql_nulls_not_distinct=False)
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.id'], name=op.f('layer_topology_id_fkey')),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name=op.f('layer_pkey')),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name=op.f('layer_schema_name_table_name_feature_column_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('topology',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hasz', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('useslargeids', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('topology_pkey')),
    sa.UniqueConstraint('name', name=op.f('topology_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='topology'
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.create_table('topology',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('precision', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('hasz', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('useslargeids', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('topology_pkey')),
    sa.UniqueConstraint('name', name=op.f('topology_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('layer',
    sa.Column('topology_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('layer_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('schema_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_column', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('feature_type', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('child_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['topology_id'], ['topology.topology.id'], name=op.f('layer_topology_id_fkey')),
    sa.PrimaryKeyConstraint('topology_id', 'layer_id', name=op.f('layer_pkey')),
    sa.UniqueConstraint('schema_name', 'table_name', 'feature_column', name=op.f('layer_schema_name_table_name_feature_column_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='topology'
    )
    # ### end Alembic commands ###
